# http://module-build.sourceforge.net/META-spec.html
name:         SystemPerl
version:      1.320
version_from: Netlist.pm
license:      perl
installdirs:  site
requires:
    Pod::Usage:                    0
    Verilog::Getopt:               2.211
    Verilog::Netlist:              2.315

distribution_type: module
