# http://module-build.sourceforge.net/META-spec.html
name:         SystemPerl
version:      1.170
version_from: Netlist.pm
license:      perl
installdirs:  site
requires:
    Verilog::Getopt:               2.211
    Verilog::Netlist:              2.31

distribution_type: module
